branch-defaults:
  main:
    environment: artist-portfolio-env
    group_suffix: null
global:
  application_name: artist-portfolio
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
