branch-defaults:
  main:
    environment: null
    group_suffix: null
deploy:
  artifact: build.zip
environment-defaults:
  artist-portfolio-env:
    branch: null
    repository: null
  artist-portfolio-prod:
    branch: null
    repository: null
global:
  application_name: artist-portfolio
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
